export const NAV = 'NAV'

export const GET_FOOD_LIST = 'GET_FOOD_LIST'
export const GET_FOOD_LIST_SUCCESS = 'GET_FOOD_LIST_SUCCESS'
export const GET_FOOD_LIST_ERROR = 'GET_FOOD_LIST_ERROR'

export const CREATE_FOOD_ITEM = 'CREATE_FOOD_ITEM'
export const CREATE_FOOD_ITEM_SUCCESS = 'CREATE_FOOD_ITEM_SUCCESS'
export const CREATE_FOOD_ITEM_ERROR = 'CREATE_FOOD_ITEM_ERROR'

export const GET_FOOD_ITEM = 'GET_FOOD_ITEM'
export const GET_FOOD_ITEM_SUCCESS = 'GET_FOOD_ITEM_SUCCESS'
export const GET_FOOD_ITEM_ERROR = 'GET_FOOD_ITEM_ERROR'

export const UPDATE_FOOD_ITEM = 'UPDATE_FOOD_ITEM'
export const UPDATE_FOOD_ITEM_SUCCESS = 'UPDATE_FOOD_ITEM_SUCCESS'
export const UPDATE_FOOD_ITEM_ERROR = 'UPDATE_FOOD_ITEM_ERROR'

export const DELETE_FOOD_ITEM = 'DELETE_FOOD_ITEM'
export const DELETE_FOOD_ITEM_SUCCESS = 'DELETE_FOOD_ITEM_SUCCESS'
export const DELETE_FOOD_ITEM_ERROR = 'DELETE_FOOD_ITEM_ERROR'
